name: ci

permissions:
  contents: read

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [21, 33]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          emulator-options: -no-snapshot -no-window -accel auto -gpu auto -noaudio -no-boot-anim -camera-back none -camera-front none
          disable-animations: true
          arch: x86
          script: ./gradlew connectedAndroidTest --stacktrace
